[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true  # 啟用 IR 模式編譯

[profile.arbitrum]
# Arbitrum-specific settings
via_ir = true

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }